#!/bin/bash
HOMEan="/home/dan/.anacron"
# Check whether 0anacron-dan was run today already
if test -r ${HOMEan}/spool/dan.daily; then
    day=`cat ${HOMEan}/spool/dan.daily`
fi
if [ `date +%Y%m%d` = "$day" ]; then
    exit 0;
fi

# Do not run jobs when on battery power
if test -x /usr/bin/on_ac_power; then
    /usr/bin/on_ac_power &> /dev/null
    if test $? -eq 1; then
    exit 0
    fi
fi

sudo -u dan -H sh -c "/usr/sbin/anacron -t ${HOMEan}/anacrontab -S ${HOMEan}/spool &> ${HOMEan}/anacron.log"
