"""Tests for the update_changelog script.

This module tests the functions that parse and condense dependency bump entries
from release notes generated by git-cliff.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

from scripts.update_changelog import (
    PAT,
    condense_bumps,
    insert_section_at_top,
    norm_tuple,
    read_lines,
    write_text,
)


class TestNormTuple:
    """Tests for the norm_tuple function."""

    def test_simple_version(self) -> None:
        """Test simple version string."""
        assert norm_tuple("1.0.0") == (1, 0, 0)

    def test_version_with_v_prefix(self) -> None:
        """Test version string with v prefix."""
        assert norm_tuple("v1.2.3") == (1, 2, 3)

    def test_version_with_capital_v_prefix(self) -> None:
        """Test version string with V prefix."""
        assert norm_tuple("V2.0.0") == (2, 0, 0)

    def test_version_with_prerelease(self) -> None:
        """Test version string with prerelease suffix."""
        # The norm_tuple function splits on - and only captures numeric leading parts
        # So "1.2.3-beta.1" -> parts = ["1", "2", "3", "beta", "1"]
        # It stops at "beta" since it's not numeric, so only (1, 2, 3) is captured
        assert norm_tuple("1.2.3-beta.1") == (1, 2, 3)

    def test_version_with_plus(self) -> None:
        """Test version string with build metadata."""
        assert norm_tuple("1.2.3+build") == (
            1,
            2,
            3,
        )

    def test_empty_string(self) -> None:
        """Test empty string returns default tuple."""
        assert norm_tuple("") == (0,)

    def test_non_numeric_version(self) -> None:
        """Test non-numeric version string."""
        assert norm_tuple("latest") == (0,)


class TestPATRegex:
    """Tests for the PAT regex pattern."""

    def test_matches_deps_bump(self) -> None:
        """Test matching a deps bump line."""
        line = "- *(deps)* Bump xmltodict from 1.0.0 to 1.0.2 (#123)"
        match = PAT.match(line)
        assert match is not None
        groups = match.groups()
        assert groups[2] == "deps"  # tag
        assert groups[3] == "xmltodict"  # package
        assert groups[4] == "1.0.0"  # from version
        assert groups[5] == "1.0.2"  # to version

    def test_matches_action_bump(self) -> None:
        """Test matching an action bump line."""
        line = "- *(deps)* Bump actions/checkout action from v4 to v5 (#1187)"
        match = PAT.match(line)
        assert match is not None
        groups = match.groups()
        assert groups[2] == "deps"
        assert groups[3] == "actions/checkout"
        assert groups[4] == "v4"
        assert groups[5] == "v5"

    def test_matches_precommit_hook_bump(self) -> None:
        """Test matching a pre-commit hook bump line."""
        line = (
            "- *(hooks)* Bump pre-commit hook executablebooks/mdformat "
            "from 0.7.17 to 0.7.22 (#1065)"
        )
        match = PAT.match(line)
        assert match is not None
        groups = match.groups()
        assert groups[2] == "hooks"
        assert groups[3] == "executablebooks/mdformat"
        assert groups[4] == "0.7.17"
        assert groups[5] == "0.7.22"

    def test_does_not_match_non_bump_line(self) -> None:
        """Test that non-bump lines don't match."""
        line = "- *(feat)* Add new feature"
        match = PAT.match(line)
        assert match is None


class TestCondenseBumps:
    """Tests for the condense_bumps function."""

    def test_condenses_multiple_bumps_same_package(self) -> None:
        """Test condensing multiple bumps of the same package."""
        lines = [
            "- *(deps)* Bump pkg-a from 1.0.0 to 1.1.0 (#1)\n",
            "- *(deps)* Bump pkg-a from 1.1.0 to 1.2.0 (#2)\n",
            "- *(deps)* Bump pkg-a from 1.2.0 to 2.0.0 (#3)\n",
        ]
        result = condense_bumps(lines, {"deps"})
        assert len(result) == 1
        assert "from 1.0.0 to 2.0.0" in result[0]

    def test_preserves_non_bump_lines(self) -> None:
        """Test that non-bump lines are preserved."""
        lines = [
            "- *(feat)* Add new feature\n",
            "- *(deps)* Bump pkg-a from 1.0.0 to 2.0.0 (#1)\n",
            "- *(fix)* Fix bug\n",
        ]
        result = condense_bumps(lines, {"deps"})
        assert len(result) == 3
        assert "Add new feature" in result[0]
        assert "Fix bug" in result[2]

    def test_keeps_bumps_with_different_tags(self) -> None:
        """Test that bumps with different tags are kept separate."""
        lines = [
            "- *(deps)* Bump pkg-a from 1.0.0 to 2.0.0 (#1)\n",
            "- *(hooks)* Bump pkg-b from 1.0.0 to 2.0.0 (#2)\n",
        ]
        result = condense_bumps(lines, {"deps", "hooks"})
        assert len(result) == 2

    def test_ignores_tags_not_in_allowed_set(self) -> None:
        """Test that tags not in allowed set are not condensed."""
        lines = [
            "- *(docs)* Bump doc-tool from 1.0.0 to 1.1.0 (#1)\n",
            "- *(docs)* Bump doc-tool from 1.1.0 to 2.0.0 (#2)\n",
        ]
        result = condense_bumps(lines, {"deps"})
        # Both lines should be preserved since 'docs' is not in allowed_tags
        assert len(result) == 2


class TestInsertSectionAtTop:
    """Tests for the insert_section_at_top function."""

    def test_inserts_before_first_release_heading(self) -> None:
        """Test insertion before first release heading."""
        changelog_lines = [
            "# Changelog\n",
            "\n",
            "## [1.0.0] - 2024-01-01\n",
            "\n",
            "- Initial release\n",
        ]
        section = [
            "## [1.1.0] - 2024-02-01\n",
            "\n",
            "- New feature\n",
        ]
        result = insert_section_at_top(changelog_lines, section)
        # Check that new section is before old release
        assert result.index("## [1.1.0]") < result.index("## [1.0.0]")

    def test_handles_empty_changelog(self) -> None:
        """Test handling of empty changelog."""
        changelog_lines = ["# Changelog\n"]
        section = ["## [1.0.0] - 2024-01-01\n", "- Initial release\n"]
        result = insert_section_at_top(changelog_lines, section)
        assert "## [1.0.0]" in result

    def test_normalizes_trailing_newlines(self) -> None:
        """Test that result has exactly one trailing newline."""
        changelog_lines = ["# Changelog\n", "\n", "\n"]
        section = ["## [1.0.0] - 2024-01-01\n"]
        result = insert_section_at_top(changelog_lines, section)
        assert result.endswith("\n")
        assert not result.endswith("\n\n")


class TestFileOperations:
    """Tests for read_lines and write_text functions."""

    def test_read_write_roundtrip(self) -> None:
        """Test reading and writing files."""
        with tempfile.NamedTemporaryFile(
            encoding="utf-8", mode="w", suffix=".txt", delete=False
        ) as f:
            f.write("line 1\nline 2\nline 3\n")
            temp_path = f.name

        try:
            lines = read_lines(temp_path)
            assert len(lines) == 3
            assert lines[0] == "line 1\n"

            write_text(temp_path, "new content\n")
            new_lines = read_lines(temp_path)
            assert len(new_lines) == 1
            assert new_lines[0] == "new content\n"
        finally:
            Path(temp_path).unlink()
