// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("ArtalkUser", '{"email":"darosio","name":"darosio"}');
user_pref("extensions.ui.dictionary.hidden", false);
user_pref("extensions.zotero.attachmentRenameTemplate", '{{ title truncate="50" }}');
user_pref("extensions.zotero.autoRenameFiles.fileTypes", "application/pdf,application/epub+zip,image/,audio/,video/");
user_pref("extensions.zotero.autoRenameFiles.linked", true);
/* user_pref("extensions.zotero.automaticTags", false); */
user_pref("extensions.zotero.fileHandler.epub", "system");
user_pref("extensions.zotero.fileHandler.snapshot", "system");
user_pref("extensions.zotero.firstRunGuidanceShown.quickFormat", true);
user_pref("extensions.zotero.groups.copyChildFileAttachments", false);
user_pref("extensions.zotero.groups.copyChildLinks", false);
user_pref("extensions.zotero.groups.copyChildNotes", false);
user_pref("extensions.zotero.groups.copyTags", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.panes.abstract.open", false);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", false);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.sync.server.username", "darosio");
user_pref("extensions.zotero.sync.storage.enabled", false);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.capitalize + year + "_" + authorLast(initials=true).capitalize");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.capitalize + year + "_" + authorLast(initials=true).capitalize");
user_pref("extensions.zotero.translators.better-bibtex.extraMergeCSL", true);
user_pref("extensions.zotero.translators.better-bibtex.extraMergeTeX", true);
user_pref("extensions.zotero.translators.better-bibtex.keyConflictPolicy", "change");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/usr/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.translators.better-bibtex.qualityReport", true);
user_pref("extensions.zotero.translators.better-bibtex.quickCopyMode", "pandoc");
user_pref("extensions.zotero.translators.better-bibtex.quickCopyPandocBrackets", true);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotero.zoteroaddons.firstInstalledVersion", "2.1.1");
user_pref("extensions.zotero.zoteroaddons.guideStatus", 1);
user_pref("extensions.zotmoov.allowed_fileext", '["pdf","epub","docx","djvu","doc","txt","rtf","zip","xlsx","xls"]');
user_pref("extensions.zotmoov.delete_files", true);
user_pref("extensions.zotmoov.dst_dir", "/home/dan/Sync/biblio/main");
user_pref("extensions.zotmoov.enable_subdir_move", true);
user_pref("extensions.zotmoov.subdirectory_string", "{%b}");
user_pref("intl.accept_languages", "en-US, en");
