" Main config {{{
set modelines=1		" modeline must be within first or last 1 line
set autoread			" Set to auto read when a file is changed from the outside
hi DiffText gui=underline guibg=red guifg=black
inoremap <expr> <CR> pumvisible() ? '<C-Y>' : '<CR>' " Select the item in lists with enter
autocmd FileType html setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType c set omnifunc=ccomplete#Complete
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
set nocompatible    "disable vi"
syntax enable
set lazyredraw " Don't redraw while executing macros (good performance config)
set laststatus=2								" Always show the status line
set ttyfast											" faster redraw (with multiple windows)
set backspace=eol,start,indent	" or =2 although not needed in Arch
set whichwrap+=<,>,h,l					" to continue on next/previous line"
set shortmess=atI
set autochdir
set fileencoding=utf-8
set encoding=utf-8
runtime macros/matchit.vim			" more matches using %, like def/end in Ruby
set viminfo^=%									" Remember info about open buffers on close
" Keybindings
let mapleader=','
let g:mapleader=','
nmap <Leader>h :exe ':h '.expand('<cword>')<CR>
nnoremap <leader>r <ESC>:redraw!<CR> " redraw screen
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
map <silent> <leader>sv :source ~/.vim/vimrc<CR>:filetype detect<CR> " Reload .vimrc
map <silent> <leader>ev :vsp ~/.vim/vimrc<CR>												 " Open .vimrc
command! Sudow :w !sudo tee % >/dev/null " for when we forget to use sudo
nnoremap ;w :w<CR>
nnoremap ;q :q<CR>
nnoremap <leader>qq :q!<CR>
nmap <leader>wq :wq<CR>
nmap ; :
" whitespaces
set listchars=tab:>.,trail:·,eol:$,extends:#,nbsp:.
nmap <silent> <leader>ll :set nolist!<CR> " Show
nnoremap <leader>llr :%s/\s\+$//<cr>:let @/=''<CR> " Remove
" copy and paste
vnoremap <leader>y "+y
vmap <C-c> "+y
nmap <C-c> "+yiw
map <leader>pp "+gP
map <leader>p "+p

set history=700
set number											" line numbers
nmap <C-N> :set invnumber<CR>
set cursorline							" highlight current line
set wildmenu								" visual autocomplete for command menu
set showmatch								" highlight matvching [{()}]
set textwidth=79						" line wrapped after 80 columns
set wrap										" wrap text line longer then 80 chars
set linebreak								" do not break a word in two lines when wrapping
" move vertically accross fake wrapped lines
nnoremap j gj
nnoremap k gk
nnoremap gV `[v`]			" highlight inserted text during last INSERT mode
set nostartofline			" Avoid moving cursor to BOL when jumping around
set virtualedit=block	" Let cursor move past the last char in <C-v> mode
set scrolloff=3				" Keep 3 context lines above and below the cursor
set title							" show title in console title bar
set colorcolumn=80		" show color at column 80
highlight ColorColumn ctermbg=green guibg=darkred
set noerrorbells							" don't beep
set visualbell t_vb=					" Disable all bells.  I hate ringing/flashing.
set nobackup									" Use SVN, hg, git, rsnapshot, unison ...
set noswapfile
" Spaces & Tabs & moving around
set autoindent			" always autoindent on
set tabstop=4				" number of visual spaces per TAB
set softtabstop=4		" number of spaces per TAB when editing
set shiftwidth=4		" number of spaces per indent
set shiftround			" round indent to multiple of 'shiftwidth'
set smarttab				" backspace over tabs
set copyindent			" copy indent structure, spaces and tabs from upper line
" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" ( <C-O> makes next cmd happen as if in command mode )
imap <C-W> <C-O><C-W>
nmap <Leader>q :bd<CR>					"Close current buffer
" Useful mappings for managing tabs FIXME @check tab?
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove<cr>
" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/
" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
	\ if line("'\"") > 0 && line("'\"") <= line("$") |
	\   exe "normal! g`\"" |
	\ endif
" folding
set foldenable		" enable folding
set foldlevelstart=7 " open most folds by default
set foldnestmax=10	" creates 10 fold levels at maximum
nnoremap <tab> za
" spelling
for d in glob('~/.vim/spell/*.add', 1, 1)
	if filereadable(d) && (!filereadable(d . '.spl') || getftime(d) > getftime(d . '.spl'))
		silent exec 'mkspell! ' . fnameescape(d)
	endif
endfor
" Ignore these files when completing
set wildignore+=*.o,*.obj,.git,*.pyc
set wildignore+=eggs/**
set wildignore+=*.egg-info/**
" make <F5> (Makefile)
nnoremap <F5> :w<CR> :silent make<CR> :redraw!<CR>
inoremap <F5> <Esc>:w<CR>:silent make<CR> :redraw!<CR>
vnoremap <F5> :<C-U>:w<CR>:silent make<CR> :redraw!<CR>
" Searching	
set ignorecase		" ignore case
set smartcase		" try to be smart
set incsearch		" search as characters are entered
set hlsearch		" highlight search results
nnoremap <leader><space> :nohlsearch<cr> " turn off highlight matches
" gvim
set guifont=IBM\ Plex\ Mono\ Text\ 11	" for gvim only
set guioptions=aegim	" a visual mode copy/paste, m menu, g gray menu ...
set guioptions-=T   	" do not show Toolbars in gvim
set diffopt+=iwhite	" ignore white spaces in gvimdiff
if has('gui_running')
	set antialias
	autocmd GuiEnter * set columns=95
	if &diff
		autocmd GuiEnter * set columns=165 lines=50
		set guifont=Monaco\ 10
	end
end
" }}}

" Bundle {{{
set nocompatible
filetype off										"required!
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
"git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
Plugin 'VundleVim/Vundle.vim'		"let Vundle manage Vundle, required
Plugin 'vim-scripts/tasklist.vim'
Plugin 'tpope/vim-speeddating'
Plugin 'dhruvasagar/vim-table-mode'
let g:table_mode_corner_corner='+' "ReST-compatible tables use
let g:table_mode_header_fillchar='='
" Writing_Prose:
Plugin 'vimoutliner/vimoutliner'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'vim-pandoc/vim-pandoc-after'
" Rmd and Rpres are pandoc
"au BufRead,BufNewFile *.Rmd,*.Rpres setfiletype pandoc
au BufRead,BufNewFile *.Rmd setfiletype markdown
Plugin 'dpelle/vim-LanguageTool'
let g:languagetool_cmd='/usr/bin/languagetool'
"Plugin 'reedes/vim-lexical'
" Special_files
Plugin 'bioSyntax/bioSyntax-vim'
Plugin 'aklt/plantuml-syntax'
" let g:plantuml_executable_script='java -jar c:\utils\plantuml\plantuml.jar'
Plugin 'chrisbra/csv.vim'
" Git:
Plugin 'mhinz/vim-signify' " works also for hg 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-unimpaired'
Plugin 'gregsexton/gitv'
Plugin 'tommcdo/vim-fubitive'   " Gbrowse for bitbucket
" IDE:
Plugin 'scrooloose/nerdcommenter' " ,cc
" @jeff: Eclim, IndentLine, Delimitmate, vim-rooter
Plugin 'SirVer/ultisnips'
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<s-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
Plugin 'ervandew/supertab.git' "@j @S
" Ctrl-v Tab : when a real Tab is meant
" useful to know: ":verbose imap <tab>"
" currently use ultisnip completion
let g:SuperTabDefaultCompletionType = "context"
Plugin 'honza/vim-snippets'
" Others:
Plugin 'tpope/vim-surround'			" braces @S @sf``
Plugin 'jiangmiao/auto-pairs'		" braces
call vundle#end()								" required
filetype plugin indent on				" required
filetype plugin on				" required
" }}}
" vim-wordy {{{
" Passive voice and such
Plugin 'reedes/vim-wordy'
let g:wordy#ring = [
  \ 'weak',
  \ ['being', 'passive-voice', ],
  \ 'business-jargon',
  \ 'weasel',
  \ 'puffery',
  \ ['problematic', 'redundant', ],
  \ ['colloquial', 'idiomatic', 'similies', ],
  \ 'art-jargon',
  \ ['contractions', 'opinion', 'vague-time', 'said-synonyms', ],
  \ 'adjectives',
  \ 'adverbs',
  \ ]
noremap <silent> <F8> :<C-u>NextWordy<cr>
xnoremap <silent> <F8> :<C-u>NextWordy<cr>
inoremap <silent> <F8> <C-o>:NextWordy<cr>
" }}}
" FZF {{{
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plugin 'junegunn/fzf.vim'
noremap <nowait><Leader>b :Buffers<CR>
nnoremap <nowait><Leader>f :Files<CR>
"set rtp+=~/.fzf
" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)
" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)
"}}}
" airline {{{
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#enabled = 1
" Show just the filename
"let g:airline#extensions#tabline#fnamemod = ':t'
" Use nicer graph font
let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#left_sep = ' '
"let g:airline#extensions#tabline#left_alt_sep = '|'
" }}}
" ctags{{{
Plugin 'preservim/tagbar'
nmap <F9> :TagbarToggle<CR>
" tagbar markdown (markdown2ctags)
let g:tagbar_type_markdown = {
	\ 'ctagstype': 'markdown',
	\ 'ctagsbin' : '/usr/bin/markdown2ctags',
	\ 'ctagsargs' : '-f - --sort=yes',
	\ 'kinds' : [
		\ 's:sections',
		\ 'i:images'
	\ ],
	\ 'sro' : '|',
	\ 'kind2scope' : {
		\ 's' : 'section',
	\ },
	\ 'sort': 0,
\ }
" tagbar r
let g:tagbar_type_r = {
	\ 'ctagstype' : 'r',
	\ 'kinds'     : [
		\ 'f:Functions',
		\ 'g:GlobalVariables',
		\ 'v:FunctionVariables',
	\ ]
\ }
" }}}
" ranger{{{
function! RangeChooser()
	let temp = tempname()
	if has("gui_running")
		exec 'silent !xterm -e ranger --choosefiles=' . shellescape(temp)
	else
		exec 'silent !ranger --choosefiles=' . shellescape(temp)
	endif
	if !filereadable(temp)
		redraw!
		" Nothing to read.
		return
	endif
	let names = readfile(temp)
	if empty(names)
		redraw!
		" Nothing to open.
		return
	endif
	" Edit the first item.
	exec 'edit ' . fnameescape(names[0])
	" Add any remaning items to the arg list/buffer list.
	for name in names[1:]
		exec 'argadd ' . fnameescape(name)
	endfor
	redraw!
endfunction
command! -bar RangerChooser call RangeChooser()
"nnoremap <leader>r :<C-U>RangerChooser<CR>
map <F2> :<C-U>RangerChooser<CR>
" }}}
" no distraction F11 {{{
Plugin 'junegunn/goyo.vim'
nnoremap <silent> <F11> :Goyo<cr>
" }}}
" solarized F12 {{{
Plugin 'altercation/vim-colors-solarized'
set t_Co=256
" syntax on
set background=dark	" often used with dark bg
colorscheme solarized
call togglebg#map("<F12>")
" }}}
" vim:foldmethod=marker:foldlevel=0
