set modelines=1	" modeline must be within first or last 1 line

let mapleader=','
let g:mapleader=','

" Set to auto read when a file is changed from the outside
set autoread
"set noautoread              " Don't automatically re-read changed files.
"set autowrite               " Stop complaining about unsaved buffers
"set autowriteall            " 
" Jeff
hi DiffText gui=underline guibg=red guifg=black
" Select the item in the list with enter
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" tab switch
"nnoremap <Tab> <ESC>:tabn<CR>
" Bundle {{{
filetype off                   " required!
call vundle#rc()

" Next:
" NrrwRgn
" TaskList
" VimPDB
"
"
"Plug 'ivanov/vim-ipython'
"Plug 'lervag/vim-latex'
"Plug 'wannesm/wmgraphviz.vim'
"also consider:
"easymotion
"hardmode
"hexmode
"html5
"nodejs-complete
"php
"tComment
"web-indent
"xmledit
"
""" easymotion
"""\\w move to word forwards
"""\\b move to word backwards
""" hardmode ^_^
""nnoremap <leader>h <ESC>:call ToggleHardMode()<CR>
""" snipmate
"""<c-r>tab lists snippets
""" tComment
""nnoremap <leader>c <c-_><c-_>
""vnoremap <leader>c <c-_><c-_>

" 
" Highlight a column in csv text.
" :Csv 1    " highlight first column
" :Csv 12   " highlight twelfth column
" :Csv 0    " switch off highlight
""function! CSVH(colnr)
""  if a:colnr > 1
""    let n = a:colnr - 1
""    execute 'match Keyword /^\([^,]*,\)\{'.n.'}\zs[^,]*/'
""    execute 'normal! 0'.n.'f,'
""  elseif a:colnr == 1
""    match Keyword /^[^,]*/
""    normal! 0
""  else
""    match
""  endif
""endfunction
""command! -nargs=1 Csv :call CSVH(<args>)
""
"""
" Colors:
Plugin 'tomasr/molokai'
Plugin 'sjl/badwolf'
Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-scripts/wombat256.vim'

" General:
Plugin 'scrooloose/nerdtree'
map <F2> :NERDTreeToggle<CR>
Plugin 'junegunn/goyo.vim'
nnoremap <silent> <F11> :Goyo<cr>
Plugin 'bling/vim-airline'
"Plugin 'Lokaltog/vim-easymotion'
Plugin 'ervandew/supertab.git'
let g:SuperTabDefaultCompletionType = "context"
Plugin 'majutsushi/tagbar' " ctags
" the silver searcher alternative to ctags and tagbar
Plugin 'rking/ag.vim'
nmap <C-F> :Ag 
" args `Ag -l FOOBAR .`
" argdo %s/FOO/BAR/g | w
Plugin 'junegunn/fzf'

" Diff:
Plugin 'vim-scripts/DirDiff.vim'
" Plugin 'gkirilov/vim-wdiff'
" Plugin 'vim-scripts/ShowMarks'  Not working properly

" Writing_Prose:
Plugin 'beloglazov/vim-online-thesaurus'
nnoremap <leader>k :OnlineThesaurusCurrentWord<CR>
Plugin 'vimoutliner/vimoutliner'
Plugin 'reedes/vim-wordy'
" Plugin 'reedes/vim-pencil'
" Plugin 'reedes/vim-wheel'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'vim-pandoc/vim-pandoc-after'
" Rmd and Rpres are pandoc
"au BufRead,BufNewFile *.Rmd,*.Rpres setfiletype pandoc
au BufRead,BufNewFile *.Rmd setfiletype markdown
"Plugin 'vim-pandoc/vim-rmarkdown'
"Plugin 'vim-scripts/LanguageTool'
Plugin 'rhysd/vim-grammarous'
"Plugin 'goldfeld/criticmarkup-vim'
Plugin 'junegunn/vim-easy-align'
map <F3> :exe ":!dict ".expand("<cword>")<CR>
map <F4> :exe ":!wn ".expand("<cword>") " -antsa"<CR>
map <F4> :exe ":!wn ".expand("<cword>") " -synsn -synsv -synsa -synsr"<CR>
" Passive voice and such
Plugin 'jamestomasino/vim-writingsyntax'
nnoremap <leader>P :setf writing<CR>"
Plugin 'vim-scripts/Wordnet.vim'
map <leader>ww <leader>wnd

" Special_files:
Plugin 'aklt/plantuml-syntax'
Plugin 'chrisbra/csv.vim'

" Git:
Plugin 'mhinz/vim-signify' " works also for hg 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'tommcdo/vim-fubitive'   " Gbrowse for bitbucket

" IDE:
Plugin 'scrooloose/nerdcommenter' " ,cc
"snipmate
"Plugin 'MarcWeber/vim-addon-mw-utils'
"Plugin 'tomtom/tlib_vim'
"Plugin 'garbas/vim-snipmate'
"UltiSnips
Plugin 'SirVer/ultisnips'
"june
"autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType html setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
"autocmd FileType python setlocal omnifunc=python3complete#Complete
"autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType python setlocal omnifunc=jedi#completions
"autocmd FileType c set omnifunc=ccomplete#Complete
"autocmd FileType css set omnifunc=csscomplete#CompleteCSS
"autocmd FileType php set omnifunc=phpcomplete#CompletePHP
"autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
" omni completion @FIXME
""" inoremap <c-Space> <c-x><c-o>
""" inoremap <c-@> <c-Space>
Bundle 'Shougo/neocomplete'
"Bundle 'Shougo/neosnippet'
"Bundle 'Shougo/neosnippet-snippets'
" Optional
Plugin 'honza/vim-snippets'
""" Python
Plugin 'davidhalter/jedi-vim'
"Plugin 'scrooloose/syntastic' "june
" syntasytic to directly use flake8
"Need: flake8 pep8 python-mccabe python-pyflakes
Plugin 'nvie/vim-flake8'
" Plugin 'nvie/vim-pyunit'
Plugin 'alfredodeza/pytest.vim'
Plugin 'alfredodeza/coveragepy.vim'
" Virtualenv
Plugin 'jmcantrell/vim-virtualenv'

" Others:
Plugin 'tpope/vim-surround' " braces
Plugin 'jiangmiao/auto-pairs' " braces
" }}}

"let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

set nocompatible    "disable vi"
" this order fix a problem with csv
filetype plugin indent on " load filetype-specific plugin/indent file
syntax enable
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set ttyfast		" faster redraw (with multiple windows)

" Don't redraw while executing macros (good performance config)
set lazyredraw

" redraw screen
nnoremap <leader>r <ESC>:redraw!<CR>

" Always show the status line
set laststatus=2
" partly inspired by sensible and partly from my old config
set backspace=eol,start,indent "or =2 although not needed in Arch
set whichwrap+=<,>,h,l  "to continue on next/previous line"
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
set shortmess=atI
set autochdir
" file handling
set fileencoding=utf-8
set encoding=utf-8
autocmd FileType plaintext setlocal spell spelllang=en_us,it_it color desert
" I 'd like to understand this
runtime macros/matchit.vim

" Ignore these files when completing
set wildignore+=*.o,*.obj,.git,*.pyc
set wildignore+=eggs/**
set wildignore+=*.egg-info/**

" Colors {{{
" for solarized colors
set t_Co=16
syntax on
set background=dark	" often used with dark bg
colorscheme solarized
call togglebg#map("<F12>")
" }}}
" gvim {{{
set guifont=Monaco\ 11	" font for gvim
set guioptions=aegim	" a visual mode copy/paste, m menu, g gray menu ...
set guioptions-=T   	" do not show Toolbars in gvim
set diffopt+=iwhite	" ignore white spaces in gvimdiff
if has('gui_running')
    set antialias
	autocmd GuiEnter * set columns=95
	if &diff
		autocmd GuiEnter * set columns=165 lines=50
		set guifont=Monaco\ 10
	end
	" winpos 576 329
end
" }}}
" Shortcuts {{{
" Reload Vimrc
map <silent> <leader>sv :source ~/.vim/vimrc<CR>:filetype detect<CR>
map <silent> <leader>ev :vsp ~/.vim/vimrc<CR>
" for when we forget to use sudo to open/edit a file
command! Sudow :w !sudo tee % >/dev/null
nnoremap ;w :w<CR>
nnoremap ;q :q<CR>
nnoremap <leader>qq :q!<CR>
nmap <leader>wq :wq<CR>
nnoremap ; :
" Show trailing whitespace: <leader>ll
set listchars=tab:>.,trail:·,eol:$,extends:#,nbsp:.
nmap <silent> <leader>ll :set nolist!<CR>
" Remove trailing whitespace: <leader>llr
nnoremap <leader>llr :%s/\s\+$//<cr>:let @/=''<CR>
" }}}
" copy and paste {{{
vnoremap <leader>y "+y
vmap <C-c> "+y
nmap <C-c> "+yiw
map <leader>pp "+gP
map <leader>p "+p
" toggle paste mode
set pastetoggle=<F2>
" }}}
" Spaces & Tabs & moving around {{{
set autoindent		" always autoindent on
"set smartindent		" if no indent file available
set tabstop=4		" number of visual spaces per TAB
set softtabstop=4	" number of spaces per TAB when editing
set shiftwidth=4	" number of spaces per indent
set shiftround		" round indent to multiple of 'shiftwidth'
set expandtab		" tabs are always spaces
set smarttab		" backspace over tabs
set copyindent		" copy indent structure, spaces and tabs from upper line

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
" lets make these all work in insert mode too 
" ( <C-O> makes next cmd happen as if in command mode ) FIXME
imap <C-W> <C-O><C-W>
" Close all the buffers
map <leader>ba :1,1000 bd!<cr>
" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove<cr>
" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/
" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>
" Specify the behavior when switching between buffers But it shows tab always
"try
"  set switchbuf=useopen,usetab,newtab
"  set stal=2
"catch
"endtry
" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
" Remember info about open buffers on close
set viminfo^=%
" }}}
" UI Config {{{
set history=700
" line numbers
set number
nmap <C-N> :set invnumber<CR>
"set showcmd  maybe faster?
set cursorline		" highlight current line
set wildmenu		" visual autocomplete for command menu
set showmatch		" highlight matvching [{()}]
set textwidth=79	" line wrapped after 80 columns
set wrap			" wrap text line longer then 80 chars
set linebreak		" do not break a word in two lines when wrapping
" move vertically accross fake wrapped lines
nnoremap j gj
nnoremap k gk
" highlight inserted text during last INSERT mode
nnoremap gV `[v`]
" Jeff
set nostartofline	" Avoid moving cursor to BOL when jumping around
set virtualedit=block " Let cursor move past the last char in <C-v> mode
set scrolloff=3		" Keep 3 context lines above and below the cursor
set title			" show title in console title bar
set colorcolumn=80	" show color at column 80
highlight ColorColumn ctermbg=green guibg=darkred
set noerrorbells	" don't beep
set visualbell t_vb= " Disable all bells.  I hate ringing/flashing.
" Use SVN, hg, git, rsnapshot, unison ...
set nobackup
set noswapfile
" }}}
" Searching {{{
set ignorecase		" ignore case
set smartcase		" try to be smart
set incsearch		" search as characters are entered
set hlsearch		" highlight search results
" turn off highlight matches
nnoremap <leader><space> :nohlsearch<cr>
" }}}
" Folding {{{
"myold set foldignore=
"myold set formatoptions=cqrt
" set formatoptions=tcroql    " Setting text and comment formatting to auto
set foldenable		" enable folding
set foldlevelstart=7 " open most folds by default
set foldnestmax=10	" creates 10 fold levels at maximum
" space open/closes folds
nnoremap <space> za
set foldmethod=indent	" based on indent level (manual,expr,syntax,diff)
" }}}
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""" Plugins:
" FZF {{{
nmap <C-p> :FZF<CR>
set rtp+=~/.fzf
"
" List of buffers
function! BufList()
  redir => ls
  silent ls
  redir END
  return split(ls, '\n')
endfunction

function! BufOpen(e)
  execute 'buffer '. matchstr(a:e, '^[ 0-9]*')
endfunction

nnoremap <silent> <leader>l :call fzf#run({
\   'source':      reverse(BufList()),
\   'sink':        function('BufOpen'),
\   'options':     '+m',
\   'tmux_height': '40%'
\ })<CR>
"
" Choose a color scheme with fzf
nnoremap <silent> <Leader>C :call fzf#run({
\   'source':
\     map(split(globpath(&rtp, "colors/*.vim"), "\n"),
\         "substitute(fnamemodify(v:val, ':t'), '\\..\\{-}$', '', '')"),
\   'sink':     'colo',
\   'options':  '+m',
\   'left':     20,
\   'launcher': 'xterm -geometry 20x30 -e bash -ic %s'
\ })<CR>
"}}}
" ctags{{{ 
nmap <F9> :TagbarToggle<CR>
" tagbar markdown (markdown2ctags)
let g:tagbar_type_markdown = {
    \ 'ctagstype': 'markdown',
    \ 'ctagsbin' : '/usr/bin/markdown2ctags',
    \ 'ctagsargs' : '-f - --sort=yes',
    \ 'kinds' : [
        \ 's:sections',
        \ 'i:images'
    \ ],
    \ 'sro' : '|',
    \ 'kind2scope' : {
        \ 's' : 'section',
    \ },
    \ 'sort': 0,
\ }
" tagbar r
let g:tagbar_type_r = {
    \ 'ctagstype' : 'r',
    \ 'kinds'     : [
        \ 'f:Functions',
        \ 'g:GlobalVariables',
        \ 'v:FunctionVariables',
    \ ]
\ }
" }}}
" plantuml-syntax {{{
" let g:plantuml_executable_script='java -jar c:\utils\plantuml\plantuml.jar'
nnoremap <F5> :w<CR> :silent make<CR>
inoremap <F5> <Esc>:w<CR>:silent make<CR>
vnoremap <F5> :<C-U>:w<CR>:silent make<CR
" }}}
" vim-wordy {{{
let g:wordy#ring = [
  \ 'weak',
  \ 'weasel',
  \ 'puffery',
  \ 'redundant',
  \ 'problematic',
  \ ['being', 'passive-voice', ],
  \ ['business-jargon', 'art-jargon',],
  \ ['colloquial', 'idiomatic', ],
  \ 'similies',
  \ 'said-synonyms',
  \ 'contractions',
  \ 'opinion',
  \ 'vague-time',
  \ ]
" to cycle among defined rings
nnoremap <silent> K :NextWordy<cr>
" }}}
" languagetool {{{
let g:languagetool_jar='/usr/share/java/languagetool/languagetool-commandline.jar'
"let g:DirDiffDynamicDiffText = 1
"}}}
" vim-pandoc {{{
let g:pandoc#filetypes#handled = ["pandoc", "markdown", "rst"]
" need bibtool; autocomplete using <C-X> <C-O>
let g:pandoc#biblio#use_bibtool=1
let g:pandoc#completion#bib#mode = 'citeproc'
let g:pandoc_bibfiles = ['~/Sync/00-papers.bib']
" avoid spell check of citations like @Arosio2007
syntax match myExNonWords +\<\p*[^A-Za-z \t]\p*\>+ contains=@NoSpell
let g:pandoc#folding#level = 2
let g:pandoc#folding#fdc = 4
" need this to make tagbar work
"let g:pandoc#filetypes#pandoc_markdown = 0
let g:pandoc#synatx#codeblock#embeds#langs = ['ruby', 'vim', 'python', 'r', 'json', 'c', 'julia', 'make', 'sh', 'latex']
" }}}
" vim-pandoc-after {{{
let g:pandoc#after#modules#enabled = ["supertab", "ultisnips"]
let g:pandoc#after#modules#enabled = ["ultisnips"]
" }}}
" Pytest {{{
nmap <silent><Leader>rf <Esc>:Pytest file<CR>
nmap <silent><Leader>rc <Esc>:Pytest class<CR>
nmap <silent><Leader>rm <Esc>:Pytest method<CR>
" }}}
" virtualenv {{{
let g:virtualenv_directory = '/home/dan/workspace/venvs'
let g:virtualenv_auto_activate = 1
let g:virtualenv_stl_format = '[%n]'
"%{virtualenv#statusline()}
" }}}
" autocmd FileType python setlocal completeopt-=preview
" jedi {{{
" FIXME move these into ./after/ftplugin/python.vim
" forse supertab non serve basta ctrl-space
" To disable auto-complete on .
let g:jedi#popup_on_dot = 0
let g:jedi#use_splits_not_buffers = "bottom"
" }}}
" neocomplete{{{
" Disable AutoComplPop.
let g:acp_enableAtStartup = 1
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'
" }}}

" vim:shiftwidth=2:expandtab"
"
" vim:foldmethod=marker:foldlevel=0
