#!/bin/sh

echo "### RSYNC TO vigolana DAILY ###"
sudo mount /media/rsnapshots

sudo -u dan -H sh -c "rsync -e '/usr/bin/ssh -c aes256-ctr -i /home/dan/.ssh/dan@sterzing-2013-06-03 -p 23456' -a -H --progress --delete --numeric-ids --exclude '/lost+found/' --exclude '/remotes/' /media/rsnapshots/ 192.168.1.10:/data/"  > /tmp/vigolana.daily.out 2>&1
# --checksum
#sudo -u dan -H sh -c "rsync -e '/usr/bin/ssh -c arcfour -i /home/dan/.ssh/dan@sterzing-2013-06-03 -p 23456' -a -H --progress --delete --numeric-ids --checksum /media/rsnapshots/dati vigolana:/data/dati"  > /tmp/cksum_archive.out 2>&1

cat /tmp/vigolana.daily.out 
sudo umount /media/rsnapshots
echo
