* Weekly review
          
  The heart of the GTD process is a weekly review of:
  - all projects
  - Next Action lists
  - Waiting for Items. 
  Each project is checked to ensure that a next action has been defined.
  
  Select all and toggle with =C-c C-x C-b=.
     
     - tag =, i t= or =|= or =C-c C-q= (in org file =, ,= can be used to set any tag)
     - effort =, i e= 
     - schedule/deadline =, i s=
     - =C-c C-x C-c= fill up table view simply using =e= (for edit within appropriate cell)
     - NB. to add a note  =z=  on any agenda item
  
  maybe:
  - project -> goal associatione (using tag?)
  - project template to make sure a category property is set =, i p=
  - Here C-c a m WORK/PERSONAL might highlight something needing attention
    and highlight per project “<”. items (tagged?) not TODO are also listed.
  - Review projects =F12 SPC //= and =V= repeatedly to view each project
  
  note: There is still few 2DO, FIXME, or 2MAYBE
        maybe I can improve mu4e shortcuts / bookmarks e separare mailist (confocal)
         
** *Get Clear*
*** Collect Loose Papers and Materials [3/3]
     - [X] Empty wallet of receipts and paper
     - [X] Empty backpack. Put relevant items into inbox.
     - [X] Get lose paper from desk and put it to inbox

*** Get “IN” to Zero [8/8]
     - [X] Purge physical inbox @fbk "teca nera"
     - [X] Meeting and various notes scribbled on paper notebook 
     - [X] Voice Mail
     - [X] Gmail 
       - [X] archive =j g= duplicate using =C-v=
       - [X] inbox =j j= 
       - [X] sent =j o sent/g=
       - [X] spam ...
       - [X] trash =j o trash/g=  DO NOT =C-v= Deduplicate!  =Del= (or =d=)
             restano in all mail le mail magically tagged as important.
             #+BEGIN_SRC emacs-lisp :results none
             (progn
                 (browse-url "https://mail.google.com/mail/u/0/#all")
                 (browse-url "https://mail.google.com/mail/u/0/#inbox")
                 (browse-url "https://mail.google.com/mail/u/1/#inbox"))
             #+END_SRC
     - [X] Cnr email ==j i== 
           sent, draft ... should be empty
     - [X] Clean up ~/home folders (hunza, sterzing)
           #+BEGIN_SRC emacs-lisp :results none
             (dired "~/")
           #+END_SRC
     - [X] Purge Refs folders [2/2]
       Store or delete unneded items
       - [X] cnr/refs mailbox   =j r=
       - [X] phone/box   =ranger g t=
     - [X] Browser Tabs (hunza, sterzing)
     - [X] flow (slack, twitter, google suggestion on phone ?)
             
*** Empty Your Head [1/1]
    - [X] New projects, tasks, waiting-fors, someday/maybes, etc., not yet captured

** Get Current [2/9]
 - [ ] Review Previous Calendar Data
   =, a b=  (=L)=
   Review previous week calendar and see if there is anything I missed, e.g. I
   want to follow-up to a lunch meeting with a thank you note or a gift,
   remaining action items, reference data, etc.
   #+BEGIN_SRC emacs-lisp
     (my-org-agenda-longer-open-loops)
   #+END_SRC
 - [ ] Review Upcoming Calendar and future deadlines
   =, a f=
   Review upcoming calendar long and short term. Capture actions triggered.
 - [ ] Refile tasks/projects from inbox.org
 - [X] Review Action Lists:
       #+BEGIN_SRC emacs-lisp
         (let ((org-agenda-files '("~/Sync/share/phone/box/org/gtd.org")))
           (org-agenda "TODO" "T")
           (beginend-org-agenda-mode-goto-beginning))
       #+END_SRC

   - [X] Review (next) Actions Lists  =, a w= and =, a p=
     - done: agenda without deadline (al least personal)
     - Mark off completed actions. Review for reminders of further
       action steps to record.
       - Set finished tasks to a "done" state 
       - Set reminders if necessary
       - Define follow up tasks
 - [ ] Review Standalone Tasks list
   should they be grouped into a project?
 - [ ] Review Waiting For List:
   #+BEGIN_SRC emacs-lisp
     (org-agenda "WAITING" "T")
   #+END_SRC
   - Record appropriate actions for any needed follow-up. Check off received ones.
   - This is a list of items I have delegated to others and are important enough
     to track. If something is overdue, or if I need a progress report, I send an
     e-mail and nudge the person responsible. I note in the task itself that I
     sent a reminder.
 - [X] Review Project (and Larger Outcome) Lists:
       #+BEGIN_SRC emacs-lisp
         (project-overview)
         (project-deadline-overview)
       #+END_SRC
   - [X] Review Active Project List =, a j
     Progetto := tag="proj" 
     - [X] make sure "Category" property is set; otherwise set it =, i p=
     - FIXME maybe remove all todo states
     - “What do I really need to accomplish this week?” Like goals, I either
       identity the next action and assign a due date for the day in the upcoming
       week I want to work on it or I schedule it on my calendar.
     - proj by proj “<” “^” Evaluate status of projects, goals and outcomes, one by
       one, ensuring at least one current action item on each.
     - Browse through project plans, support material, and any other
       work-in-progress material to trigger new actions, completions, waiting
       for's, etc.
 - [ ] Archive completed tasks  =$=  or inactive projects
   cfr. =, a t=  and =3 g r=
 - [ ] Review Any Relevant Checklists
  
** Get Creative [0/4]
 - [ ] Review IDEAs !! 2DO
 - [ ] Review my [[file:~/Sync/share/phone/box/notes/someday.org::*Someday][Someday]], HOLD tags and Idea lists =, a i=
   - Review for any projects which may now have become active.
   - Is a Someday/Maybe becoming a task/project?
   - If a Someday is no longer of interest set it to "Cancelled".
 - Use RandomNote https://github.com/mwfogleman/org-randomnote
   #+BEGIN_SRC emacs-lisp
     (randomnote-osx)
   #+END_SRC
 - [ ] Be Creative and Courageous
   - Any new, wonderful, hare-brained, creative, thought-provoking,
     risk-taking ideas to add into your system?
   - Set timer to 5 minutes and start dreaming
   - Put the results into Actions/Someday/Maybe.
    Capture Todo items (C-c r t) or Someday (C-c r s)  TODO
 - [ ] Clock out.
