# Please make sure that the smallest "interval" configured
# in this file is not lower than the fangfrisch.timer frequency.
# If necessary, you can override the default timer by creating
# a systemd drop-in file.
#
# When in doubt, keep the preconfigured default intervals.
# See https://rseichter.github.io/fangfrisch/ for details.
#

[DEFAULT]
db_url = sqlite:////var/lib/fangfrisch/db.sqlite
local_directory = /var/lib/clamav
on_update_exec = clamdscan --reload

[fangfrischnews]
enabled = yes

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes

[interserver]
enabled = yes

[malwarepatrol]
enabled = no
receipt = you_forgot_to_configure_receipt

[securiteinfo]
customer_id = you_forgot_to_configure_customer_id
enabled = no
